# Site settings
# -------------
baseurl     : "" # the subpath of your site, e.g. /blog/
colour      : primary
language    : nl
host        : 127.0.0.1
port        : 4000

# SEO
# ---
title      : &title Dogrun
description: "Dogrun is an application to help people find and discover new places and activities in Ghent. This is an assignment for Artevelde University College Ghent."
author     : Jodie & Niel
tracking_id: ""
# url        :
# image      :

# Build settings
# --------------
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
exclude:
  - node_modules
  - Gemfile
  - LICENSE
  - README.md